[package]
name = "healthcheckify"
version = "0.1.3"
edition = "2021"

[dependencies]
serde_json = "1.0"
reqwest = {version =  "0.11.11", features = ["blocking"]}
regex = "1"
dotenv = "0.15.0"
actix-web = "4"
tokio = { version = "1.21.2", features = ["full"] }
